I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 13, in script call
    call startChapter7 from _call_startChapter7
  File "game/chapter7.rpy", line 47, in script call
    call GameDev from _call_GameDev
  File "game/chapter7.rpy", line 205, in script
    "[renpy.random.randint(-10, 10)]"
AttributeError: 'DetRandom' object has no attribute 'randint(-10, 10)'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 13, in script call
    call startChapter7 from _call_startChapter7
  File "game/chapter7.rpy", line 47, in script call
    call GameDev from _call_GameDev
  File "game/chapter7.rpy", line 205, in script
    "[renpy.random.randint(-10, 10)]"
  File "/Users/sema/Desktop/renpy-8.1.3-sdk/renpy/ast.py", line 930, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "/Users/sema/Desktop/renpy-8.1.3-sdk/renpy/exports.py", line 1474, in say
    who(what, *args, **kwargs)
  File "/Users/sema/Desktop/renpy-8.1.3-sdk/renpy/character.py", line 1337, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "/Users/sema/Desktop/renpy-8.1.3-sdk/renpy/character.py", line 1251, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "/Users/sema/Desktop/renpy-8.1.3-sdk/renpy/character.py", line 1231, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "/Users/sema/Desktop/renpy-8.1.3-sdk/renpy/substitutions.py", line 278, in substitute
    s = formatter.vformat(s, (), kwargs) # type: ignore
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 165, in vformat
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 205, in _vformat
  File "/Users/sema/Desktop/renpy-8.1.3-sdk/renpy/substitutions.py", line 168, in get_field
    obj, arg_used = super(Formatter, self).get_field(field_name, args, kwargs)
  File "/home/tom/ab/renpy-build-fix/tmp/install.linux-x86_64/lib/python3.9/string.py", line 276, in get_field
AttributeError: 'DetRandom' object has no attribute 'randint(-10, 10)'

macOS-10.16-x86_64-i386-64bit x86_64
Ren'Py 8.1.3.23091805
Novella 1.0
Sun Dec 17 22:01:38 2023
